apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kafka.strimzi.io/v1beta2","kind":"Kafka","metadata":{"annotations":{},"name":"my-cluster","namespace":"kafka-st"},"spec":{"entityOperator":{"topicOperator":{},"userOperator":{}},"kafka":{"config":{"default.replication.factor":1,"inter.broker.protocol.version":"3.7","min.insync.replicas":1,"offsets.topic.replication.factor":1,"transaction.state.log.min.isr":1,"transaction.state.log.replication.factor":1},"listeners":[{"name":"plain","port":9092,"tls":false,"type":"internal"},{"name":"tls","port":9093,"tls":true,"type":"internal"},{"name":"external","port":9094,"tls":false,"type":"loadbalancer"}],"replicas":1,"storage":{"type":"jbod","volumes":[{"deleteClaim":false,"id":0,"size":"100Gi","type":"persistent-claim"}]},"version":"3.7.0"},"zookeeper":{"replicas":1,"storage":{"deleteClaim":false,"size":"100Gi","type":"persistent-claim"}}}}
  creationTimestamp: "2024-04-11T01:19:40Z"
  generation: 7
  name: my-cluster
  namespace: kafka-st
  resourceVersion: "108650"
  uid: 58913469-46c2-43b0-b4e6-2eab8ef9da10
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      default.replication.factor: 1
      inter.broker.protocol.version: "3.7"
      min.insync.replicas: 1
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
    listeners:
    - name: plain
      port: 9092
      tls: false
      type: internal
    - name: tls
      port: 9093
      tls: true
      type: internal
    - name: external
      port: 9094
      tls: true
      type: loadbalancer
      authentication:
        type: scram-sha-512
    authorization:
      type: simple
    replicas: 1
    storage:
      type: jbod
      volumes:
      - deleteClaim: false
        id: 0
        size: 100Gi
        type: persistent-claim
    version: 3.7.0
  zookeeper:
    replicas: 1
    storage:
      deleteClaim: false
      size: 100Gi
      type: persistent-claim
status:
  clusterId: 5YFAxT3BTa2--vsrbPwzkA
  conditions:
  - lastTransitionTime: "2024-04-11T21:24:54.047452168Z"
    status: "True"
    type: Ready
  kafkaMetadataState: ZooKeeper
  kafkaVersion: 3.7.0
  listeners:
  - addresses:
    - host: my-cluster-kafka-bootstrap.kafka-st.svc
      port: 9092
    bootstrapServers: my-cluster-kafka-bootstrap.kafka-st.svc:9092
    name: plain
  - addresses:
    - host: my-cluster-kafka-bootstrap.kafka-st.svc
      port: 9093
    bootstrapServers: my-cluster-kafka-bootstrap.kafka-st.svc:9093
    certificates:
    - |
      -----BEGIN CERTIFICATE-----
      MIIFLTCCAxWgAwIBAgIUJjBTvEdEWuAxrZYej0zha8g/qT8wDQYJKoZIhvcNAQEN
      BQAwLTETMBEGA1UECgwKaW8uc3RyaW16aTEWMBQGA1UEAwwNY2x1c3Rlci1jYSB2
      MDAeFw0yNDA0MTEwMTE5NDFaFw0yNTA0MTEwMTE5NDFaMC0xEzARBgNVBAoMCmlv
      LnN0cmltemkxFjAUBgNVBAMMDWNsdXN0ZXItY2EgdjAwggIiMA0GCSqGSIb3DQEB
      AQUAA4ICDwAwggIKAoICAQC8aeK8TJ7xewYkoWTX3AhzY0S/9d4UBp0nk/IwxyN2
      ZGeJS2S4IUDstVUj70CIO6whuewE60qrvZmExAUBtY3K0zb0CRaICm4aq9b7XgXE
      v7dYTD6+mbaj13/awzYRcjWReFhw+0TiP9Ie2HTG7M8AzLUHwNlUFjwt1+w3Vkgw
      cyjteMKafZagNduEFMP5tVlhxsAEOxYqmRq83R+wHC6bcwaP3Mddj5v0ShODnrn/
      Q72gWT496RFGtwJIjqIVtU2En7OISe7od7d0P4iFCvaK3FD+Jg5+IX4DMrU5aL56
      NC1rWMtKwfhpyc+TjjvvntI6k16kNFkXScyZL6cFYlpGdXZdBLbNLuDYUaL2uGmo
      c7PIbxpJMIcH/9N+6n9Dy2mgd02IfIMw2aHrXu/oAjDr+gvsh7w7GkifaMDYzbZJ
      0X5EngYl3rgX3D47tzrj3uN49JlESOCSP6wwCe37WPeNPHzvy15UN96qIueDl8XY
      AL2bniwbx9Hme8jcMrY+p6PibTNaFyMs87K2wiuLubkL65BHM7+prNlcFyDMautQ
      D2oVuFnp/Iv2t1VKmmiOHHMjS5M5Ldh4dwQijs88loiabvy4NYgrgrgLL8ue4Xzu
      k3wkjvt/CxPbd8SXyrRc6fDcH5CJ5luuOkAaVWpLSxW0g16r/IqFxuBcKv+9rHEj
      JwIDAQABo0UwQzAdBgNVHQ4EFgQUIjztNzfvu5guYbwqzohY0Gd3Cl8wEgYDVR0T
      AQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAQYwDQYJKoZIhvcNAQENBQADggIB
      ADx7wFYA4Csb+i6xGsz0hB7n9dDQGDjPROLBU6CMMXqEaeGZS/kiK4hhBBdjoS9t
      TSh/E0UAN5rW9f5kXbJ/UBgvuM+9ojF6IvbtJh4Ze9/Dux8Afem1mSjMzgB85UGc
      R7rhI39HpVHQdVFEsid36Es2rqA6pQybr1PNAT5tUnzTf2+Xqw9Ievy6H2j60ci+
      PU7LSO8BXfQCbddRAzpqPF9iIfoBVfoBZf4II+bpJEERUc98sSt3Aieekg7IOJNv
      egTHVuUNG7FLcuQuDDwcMBfpIhcr/btcM/RdNFY+U9FcMdx79atrx3vwDMBtYlN7
      fbaPPtuaufXZeRNva/0cD1YzI8aTy5X2F1m9GZLDR06Bp64JtgUsu1JIIfndgXZM
      1s4rRix50mtJ7ltlUgqNpH/E3BoOnShyMpbz3IHTHxdjAqclJZWu40L7CPY9f+w/
      is/XUhUkXa8lCboc29t287Epx9q9WlNmu6+XLOYq3BkNkJnrcd/Ep9u/kWeozt7G
      goe5snm/+bgJ5Tdyspj/FUkLnRDdAiJNZd8X408+4fxZi3bjhJRq05p4qxQnZw12
      dSndG0RugJsfsftHbbZOxCxnGv2+pcSmyV1jJxakVgSBorJ+eBcWfpqq3lf598OA
      icUGgyWImbDsuy+gynPAcmjsQtuGEDK1XCjbJOxSoI9+
      -----END CERTIFICATE-----
    name: tls
  - addresses:
    - host: 127.0.0.1
      port: 9094
    bootstrapServers: 127.0.0.1:9094
    certificates:
    - |
      -----BEGIN CERTIFICATE-----
      MIIFLTCCAxWgAwIBAgIUJjBTvEdEWuAxrZYej0zha8g/qT8wDQYJKoZIhvcNAQEN
      BQAwLTETMBEGA1UECgwKaW8uc3RyaW16aTEWMBQGA1UEAwwNY2x1c3Rlci1jYSB2
      MDAeFw0yNDA0MTEwMTE5NDFaFw0yNTA0MTEwMTE5NDFaMC0xEzARBgNVBAoMCmlv
      LnN0cmltemkxFjAUBgNVBAMMDWNsdXN0ZXItY2EgdjAwggIiMA0GCSqGSIb3DQEB
      AQUAA4ICDwAwggIKAoICAQC8aeK8TJ7xewYkoWTX3AhzY0S/9d4UBp0nk/IwxyN2
      ZGeJS2S4IUDstVUj70CIO6whuewE60qrvZmExAUBtY3K0zb0CRaICm4aq9b7XgXE
      v7dYTD6+mbaj13/awzYRcjWReFhw+0TiP9Ie2HTG7M8AzLUHwNlUFjwt1+w3Vkgw
      cyjteMKafZagNduEFMP5tVlhxsAEOxYqmRq83R+wHC6bcwaP3Mddj5v0ShODnrn/
      Q72gWT496RFGtwJIjqIVtU2En7OISe7od7d0P4iFCvaK3FD+Jg5+IX4DMrU5aL56
      NC1rWMtKwfhpyc+TjjvvntI6k16kNFkXScyZL6cFYlpGdXZdBLbNLuDYUaL2uGmo
      c7PIbxpJMIcH/9N+6n9Dy2mgd02IfIMw2aHrXu/oAjDr+gvsh7w7GkifaMDYzbZJ
      0X5EngYl3rgX3D47tzrj3uN49JlESOCSP6wwCe37WPeNPHzvy15UN96qIueDl8XY
      AL2bniwbx9Hme8jcMrY+p6PibTNaFyMs87K2wiuLubkL65BHM7+prNlcFyDMautQ
      D2oVuFnp/Iv2t1VKmmiOHHMjS5M5Ldh4dwQijs88loiabvy4NYgrgrgLL8ue4Xzu
      k3wkjvt/CxPbd8SXyrRc6fDcH5CJ5luuOkAaVWpLSxW0g16r/IqFxuBcKv+9rHEj
      JwIDAQABo0UwQzAdBgNVHQ4EFgQUIjztNzfvu5guYbwqzohY0Gd3Cl8wEgYDVR0T
      AQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAQYwDQYJKoZIhvcNAQENBQADggIB
      ADx7wFYA4Csb+i6xGsz0hB7n9dDQGDjPROLBU6CMMXqEaeGZS/kiK4hhBBdjoS9t
      TSh/E0UAN5rW9f5kXbJ/UBgvuM+9ojF6IvbtJh4Ze9/Dux8Afem1mSjMzgB85UGc
      R7rhI39HpVHQdVFEsid36Es2rqA6pQybr1PNAT5tUnzTf2+Xqw9Ievy6H2j60ci+
      PU7LSO8BXfQCbddRAzpqPF9iIfoBVfoBZf4II+bpJEERUc98sSt3Aieekg7IOJNv
      egTHVuUNG7FLcuQuDDwcMBfpIhcr/btcM/RdNFY+U9FcMdx79atrx3vwDMBtYlN7
      fbaPPtuaufXZeRNva/0cD1YzI8aTy5X2F1m9GZLDR06Bp64JtgUsu1JIIfndgXZM
      1s4rRix50mtJ7ltlUgqNpH/E3BoOnShyMpbz3IHTHxdjAqclJZWu40L7CPY9f+w/
      is/XUhUkXa8lCboc29t287Epx9q9WlNmu6+XLOYq3BkNkJnrcd/Ep9u/kWeozt7G
      goe5snm/+bgJ5Tdyspj/FUkLnRDdAiJNZd8X408+4fxZi3bjhJRq05p4qxQnZw12
      dSndG0RugJsfsftHbbZOxCxnGv2+pcSmyV1jJxakVgSBorJ+eBcWfpqq3lf598OA
      icUGgyWImbDsuy+gynPAcmjsQtuGEDK1XCjbJOxSoI9+
      -----END CERTIFICATE-----
    name: external
  observedGeneration: 7
  operatorLastSuccessfulVersion: 0.40.0
