apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: user-rebirth
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: instance-rebirth
          patternType: literal
        operations:
          - Describe
          - Read
          - Write
        host: "*"
      - resource:
          type: group
          name: user-rebirth
          patternType: literal
        operations:
          - Read
        host: "*"
